### ISSUE TITLE
Can't create a centered table

### ISSUE THREAD

**Issue by LarsGit223** [ssahara/dw-plugin-exttable#10]
According to the mediawiki documentation it should be possible to align a table by using **align="center"**. This sounds simple but I did not get it working. The table is displayed properley but not centered. Please provide a working example.

I use DokuWiki Hrun, the latest version of the exttab3 plugin and firefox.

**Comment by ssahara** [comment]
Please try different browser like IE or Chrome. For my case, It seems that Firefox (tested version 46.0b5) ignores **align** attribute of table tag and the table does not centered.

You can use **style** attribute for table centering: see https://www.mediawiki.org/wiki/Help:Tables#Alignment

```
{| class="wikitable" style="margin: auto;"
| Orange
|}
```

**Comment by LarsGit223** [comment]
Ok, I checked ```align="center"``` with the following browsers:
- firefox
- epiphany
- Hv3
- chrome

None of them centers the table.

If I use ```style="margin: auto;"``` then it works and the table appears centered.
(I couldn't test MS Internet Explorer cause I run my DokuWiki on a local ubuntu installation only)

**Comment by LarsGit223** [comment]
Thanks!
