### ISSUE TITLE
colspan and rowspan ignored

### ISSUE THREAD

**Issue by ternite** [ssahara/dw-plugin-exttable#19]
hi,

exttab3 ignores given rowspan and colspan attributes. They're passed to the ODT renderer as properties, ignoring the fact that rowspan and colspan have to be explicitly given to the appropriate calls via parameters. Instead of giving the correct parameters, there is always defined a fixed rowspan/colspan of "1".

I added the following 6 lines after line 32 in exttab3/helper/odt.php:
```
	$rowspan = 1;
	if (preg_match('/rowspan[ ]*=[ ]*"([0-9]*)"/', $attr, $matches) === 1) {
		$rowspan = $matches[1];
	}
	$colspan = 1;
	if (preg_match('/colspan[ ]*=[ ]*"([0-9]*)"/', $attr, $matches) === 1) {
		$colspan = $matches[1];
	}
```

The `switch` statement in line 76 got additional `$rowspan`'s and `$colspan`'s. With these changes, you can define rowspan and colspan within your wiki markup.

```
                    switch ($tag) {
                        case 'table':
                            $renderer->_odtTableOpenUseCSS(null, null, $tag, $attr);
                            break;
                        case 'caption':
                            // There is no caption in ODT table format.
                            // So we emulate it by creating a header row spaning over all columns.
                            $renderer->_odtTableRowOpenUseCSS($tag, $attr);

                            // Parameter 'colspan=0' indicates span across all columns!
                            $renderer->_odtTableHeaderOpenUseCSS(0, $rowspan, $tag, $attr);
                            break;
                        case 'th':
                            $renderer->_odtTableHeaderOpenUseCSS($colspan, $rowspan, $tag, $attr);
                            break;
                        case 'tr':
                            $renderer->_odtTableRowOpenUseCSS($tag, $attr);
                            break;
                        case 'td':
                            $renderer->_odtTableCellOpenUseCSS($colspan, $rowspan, $tag, $attr);
                            break;
                    }
```

Please excuse me that I'm not providing these changes via git, but I'm not very familiar with doing so and I'm afraid it will take more time than I have at this moment, so I'm giving my insights the way I do here.

I also appended my odt.php as txt file ([odt.php.txt](https://github.com/ssahara/dw-plugin-exttable/files/6134911/odt.php.txt)). File upload filter won't let me upload php files.

**Comment by ssahara** [comment]
@ternite , thanks for your contribution.
I would like to add **@author** line in helper/odt.php file. Is it ok for you?

**Comment by ternite** [comment]
> I would like to add **@author** line in helper/odt.php file. Is it ok for you?

That would be ok for me, but there is no need as this is just a marginal contribution. Do as you see fit! :)
